/**
 * Swahili Content — Biashara AI Company Website
 * Complete i18n translations for all sections
 */
window.SwahiliContent = {
  // ── Navigation ──
  'nav.home': 'Nyumbani',
  'nav.workers': 'Kwa Wafanyakazi',
  'nav.buyers': 'Kwa Wanunuzi',
  'nav.about': 'Kutuhusu',
  'nav.contact': 'Wasiliana',
  'nav.download': 'Pata App',

  // ── Hero ──
  'hero.badge': '🇰🇪 Nairobi, Kenya — Tujenga mustakabali wa data ya kiuchumi',
  'hero.title.line1': 'Kufanya Uchumi',
  'hero.title.line2': 'Usioonekana wa Afrika',
  'hero.title.line3': 'Uonekane.',
  'hero.subtitle': 'Wafanyakazi milioni 200 wasio rasmi. Pato la dola trilioni 1.3 kwa mwaka. Data sufuri. Hadi sasa.',
  'hero.cta.worker': 'Mimi ni Mfanyakazi',
  'hero.cta.business': 'Mimi ni Biashara',
  'hero.proof.workers': 'Wafanyakazi Wasio Rasmi',
  'hero.proof.output': 'Pato la Mwaka',
  'hero.proof.digitized': 'Iliyodijitali (hadi sasa)',

  // ── Problem ──
  'problem.label': 'Tatizo',
  'problem.title': '85% ya ajira ya Afrika ni isiyo rasmi. Hakuna mtu anaiona.',
  'problem.desc': 'Serikali zinapanga kwa upofu. Benki haziwezi kukopesha. Kampuni za FMCG zinadhani mahitaji. Wafanyakazi hawajui kama wanapata faida.',
  'problem.stat.workers': 'Wafanyakazi milioni 200+ wasio rasmi Afrika',
  'problem.stat.output': 'Pato la kiuchumi la mwaka',
  'problem.stat.digitized': 'Iliyodijitali (hadi Msaidizi)',
  'problem.stat.protests': 'Vifo zaidi ya 39 maandamano Kenya 2024 (kushindwa kwa utawala)',
  'problem.quote': '"Huwezi kudhibiti kile usichoweza kupima. Na sasa, uchumi wa Afrika mostly haujapimwa."',

  // ── Solution ──
  'solution.label': 'Suluhisho',
  'solution.title': 'Msaidizi — Msaidizi wa AI unaotumia sauti na kufanya kazi bila internet kwenye simu yoyote ya Android',
  'solution.workers.title': 'Kwa Wafanyakazi',
  'solution.workers.l1': 'Rekodi mauzo kwa sauti kwa Kiswahili',
  'solution.workers.l2': 'Fuatilia faida otomatiki',
  'solution.workers.l3': 'Pata ushauri wa biashara',
  'solution.workers.l4': 'Inafanya kazi bila internet',
  'solution.workers.l5': 'Bure milele',
  'solution.buyers.title': 'Kwa Wanunuzi',
  'solution.buyers.l1': 'Data ya mahitaji ya wakati halisi kutoka masoko yasiyo rasmi',
  'solution.buyers.l2': 'Ujasusi wa kiuchumi wa ukweli wa ardhi',
  'solution.buyers.l3': 'Iliyofichwa, iliyojumuishwa, ya kimaadili',
  'solution.buyers.l4': 'Ufikiaji wa API',
  'solution.chat1': 'Leo nimeuza vitu 5 kwa elfu kumi kila moja',
  'solution.chat2': 'Sawa! Mauzo ya leo: 50,000. Gharama: 30,000. Faida: 20,000. Kazi nzuri! 🎉',
  'solution.chat3': 'Naomba deni ya Bi Mwana',
  'solution.chat4': 'Bi Mwana anadaiwa 5,000. Aliahidi kulipa Ijumaa.',
  'solution.chat.placeholder': '🎤 Ongeza au andika...',

  // ── Workers ──
  'workers.label': 'Kwa Wafanyakazi',
  'workers.title': 'Sema na biashara yako. Simama na maarifa.',
  'workers.subtitle': 'Ongeza na biashara yako. Simama na maarifa. Msaidizi ni msaidizi wako wa biashara unaotumia sauti na kufanya kazi bila internet.',
  'workers.step1.title': 'Ongeza',
  'workers.step1.desc': 'Mwambie Msaidizi mauzo yako kwa Kiswahili. "Nimeuza vitu 5 kwa elfu kumi."',
  'workers.step2.title': 'Elewa',
  'workers.step2.desc': 'Msaidizi anarekodi, anahesabu, na anakumbuka kila kitu kwako.',
  'workers.step3.title': 'Kua',
  'workers.step3.desc': 'Jua faida yako. Fanya maamuzi bora. Kuza biashara yako.',
  'workers.download': 'Pakua Msaidizi APK',
  'workers.meta': 'Android 6.0+ · 15MB · Bure milele · Hakuna matangazo',
  'workers.community': 'Jiunge na wajasiriamali zaidi ya 1,000 katika jumuiya yetu ya WhatsApp:',
  'workers.whatsapp': 'Jiunge na Kikundi cha WhatsApp',
  'workers.card.voice.title': 'Ingizo la Sauti',
  'workers.card.voice.desc': 'Ongeza mauzo yako kwa Kiswahili au Sheng. Hakuna uhitaji wa kuandika.',
  'workers.card.offline.title': 'Inafanya Kazi Bila Internet',
  'workers.card.offline.desc': 'Hakuna internet? Hakuna tatizo. Kila kitu kinafanya kazi kwenye simu yako.',
  'workers.card.profit.title': 'Kufuatilia Faida',
  'workers.card.profit.desc': 'Ona faida na hasara yako ya kila siku. Jua kama unapata pesa.',
  'workers.card.debts.title': 'Kumbukumbu ya Deni',
  'workers.card.debts.desc': 'Usisahau mtu yeyote anayekudai. Msaidizi anakumbuka kila deni.',

  // ── Buyers ──
  'buyers.label': 'Kwa Wanunuzi',
  'buyers.title': 'Ujasusi wa Kiuchumi kutoka Uchumi Usio Rasmi wa Afrika',
  'buyers.desc': 'Data ya wakati halisi, ukweli wa ardhi kutoka masoko zaidi ya 100,000 yasiyo rasmi. Iliyofichwa. Iliyojumuishwa. Ya kimaadili.',
  'buyers.product.demand.title': 'Kutabiri Mahitaji',
  'buyers.product.demand.desc': 'Mifano ya mahitaji ya wakati halisi kutoka masoko zaidi ya 100,000 yasiyo rasmi. Jua kinachouzwa, wapi, na lini.',
  'buyers.product.demand.tag': 'FMCG · Rejea · Usambazaji',
  'buyers.product.heatmap.title': 'Ramapo za Joto za Kiuchumi',
  'buyers.product.heatmap.desc': 'Ramapo za shughuli kwa mipango ya miundombinu. Ona mahali shughuli za kiuchumi zinakusanyika.',
  'buyers.product.heatmap.tag': 'Serikali · NGO · Maendeleo',
  'buyers.product.credit.title': 'Alama za Mkopo',
  'buyers.product.credit.desc': 'Masharti ya kukopesha kulingana na miamala kwa wasio na akaunti ya benki. Kopesha kwa ujasiri.',
  'buyers.product.credit.tag': 'Benki · Mikopo Ndogo · Fintech',
  'buyers.product.policy.title': 'Athari za Sera',
  'buyers.product.policy.desc': 'Pima athari za sera kwa biashara ndogo ndogo kwa wakati halisi. Ona athari kabla ya ripoti kuja.',
  'buyers.product.policy.tag': 'Serikali · Utafiti · Maendeleo',
  'buyers.categories.title': 'Nani Ananunua Ujasusi Wetu?',
  'buyers.cat.fmcg.title': 'Kampuni za FMCG',
  'buyers.cat.fmcg.desc': '"Jua dukawallahs wanauza nini kabla ya wasambazaji wako kujua."',
  'buyers.cat.gov.title': 'Serikali',
  'buyers.cat.gov.desc': '"Panga na data ya kweli, sio makadirio."',
  'buyers.cat.banks.title': 'Benki',
  'buyers.cat.banks.desc': '"Kopesha wasio na akaunti ya benki kwa ujasiri."',
  'buyers.cat.ngo.title': 'NGO',
  'buyers.cat.ngo.desc': '"Pima athari na data ya ukweli wa ardhi."',
  'buyers.cta.title': 'Tayari kuona uchumi usio rasmi wa Afrika?',
  'buyers.cta.desc': 'Omba demo na ugundue jinsi ujasusi wa kiuchumi wa ukweli wa ardhi unavyoweza kubadilisha biashara yako.',
  'buyers.cta.whatsapp': 'Omba Demo kupitia WhatsApp',
  'buyers.cta.email': 'Tutumie Barua Pepe',

  // ── Testimonials ──
  'testimonials.label': 'Ushahidi',
  'testimonials.title': 'Inaaminiwa na wafanyakazi kote Afrika Mashariki',
  'testimonials.t1.quote': '"Sasa najua faida yangu kila siku. Kabla, nilikuwa natadhani tu. Msaidizi imebadilisha jinsi ninaendesha duka langu."',
  'testimonials.t1.name': 'Mama Amina',
  'testimonials.t1.role': 'Mmiliki wa Duka, Kariakoo',
  'testimonials.t2.quote': '"Ninapenda kwamba inafanya kazi bila internet. Soko langu halina WiFi lakini Msaidizi bado inafanya kazi kikamilifu."',
  'testimonials.t2.name': 'Juma',
  'testimonials.t2.role': 'Muuzaji wa Chakula, Gikomba',
  'testimonials.t3.quote': '"Watoto wangu walinishawishi kupakua. Sasa ninaona biashara yangu kwenye simu yangu. Ni rahisi sana."',
  'testimonials.t3.name': 'Mama Njeri',
  'testimonials.t3.role': 'Mama Ntilie, Kawangware',

  // ── About ──
  'about.label': 'Kutuhusu',
  'about.title': 'Biashara AI Ltd — Nairobi, Kenya',
  'about.mission.title': 'Dhamira Yetu',
  'about.mission.text': 'Kufanya uchumi usioonekana wa Afrika uonekane, muamala mmoja kwa wakati.',
  'about.story.title': 'Hadithi Yetu',
  'about.story.p1': 'Ilianza na swali moja: <strong>Kwa nini biashara ya mama yangu haina data?</strong>',
  'about.story.p2': 'Anauza mandazi Gikomba. Anafanya kazi kwa bidii zaidi kuliko CEO yeyote. Lakini hakuna benki inayemwona. Hakuna serikali inayemhesabu. Hakuna kampuni inayechunguza soko lake.',
  'about.story.p3': 'Biashara AI inabadilisha hilo. Tunajenga miundombinu ya data kwa uchumi usio rasmi wa Afrika — tukianza na wafanyakazi wenyewe.',
  'about.team.title': 'Timu',
  'about.team.valentine.role': 'Msanzu & CEO',
  'about.team.valentine.bio': 'BSc Uchumi na Takwimu. Ana shauku ya kutumia data kuwawezesha uchumi usio rasmi wa Afrika.',
  'about.team.future.name': 'Wewe?',
  'about.team.future.role': 'Mwanatimu wa Baadaye',
  'about.team.future.bio': 'Tunatafuta watu wanaotokana na dhamira. Una nia? Wasiliana nasi.',

  // ── Contact ──
  'contact.label': 'Wasiliana',
  'contact.title': 'Tuzungumze',
  'contact.desc': 'Iwe wewe ni mfanyakazi, biashara, mwekezaji, au mwandishi — tungependa kusikia kutoka kwako.',
  'contact.email.title': 'Barua Pepe',
  'contact.location': 'Nairobi, Kenya',

  // ── Footer ──
  'footer.desc': 'Kufanya uchumi usioonekana wa Afrika uonekane. Ilijengwa Nairobi kwa wafanyakazi milioni 200 wasio rasmi wa Afrika.',
  'footer.product': 'Bidhaa',
  'footer.app': 'App ya Msaidizi',
  'footer.intelligence': 'Bidhaa za Ujasusi',
  'footer.changelog': 'Mabadiliko',
  'footer.company': 'Kampuni',
  'footer.about': 'Kutuhusu',
  'footer.contact': 'Wasiliana',
  'footer.github': 'GitHub',
  'footer.connect': 'Unganisha',
  'footer.whatsapp': 'Jumuiya ya WhatsApp',
  'footer.rights': 'Haki zote zimehifadhiwa.',
  'footer.made': 'Ilijengwa Nairobi kwa wafanyakazi milioni 200 wasio rasmi wa Afrika 🌍'
};
